# Use the official Bun image
FROM oven/bun:1 AS base
WORKDIR /app

# --- Step 1: Install dependencies ---
# Install dependencies into a temp directory to cache them
FROM base AS install
RUN mkdir -p /temp/dev
COPY package.json bun.lock /temp/dev/
RUN cd /temp/dev && bun install --frozen-lockfile

# Install with --production to exclude devDependencies for the final image
RUN mkdir -p /temp/prod
COPY package.json bun.lock /temp/prod/
RUN cd /temp/prod && bun install --frozen-lockfile --production

# --- Step 2: Prerelease (Source Code) ---
FROM base AS prerelease
COPY --from=install /temp/dev/node_modules node_modules
COPY . .

# --- Step 3: Production Release ---
# Here we ignore all non-essential files to keep the image size small but kept in prerelease for debugging
FROM base AS release
COPY --from=install /temp/prod/node_modules node_modules
COPY --from=prerelease /app/src src
COPY --from=prerelease /app/package.json .
COPY --from=prerelease /app/tsconfig.json .
COPY --from=prerelease /app/drizzle drizzle
COPY --from=prerelease /app/drizzle.config.ts .

# Set environment
ENV NODE_ENV=production

# Run the app
USER bun
EXPOSE 9000/tcp
ENTRYPOINT [ "bun", "run", "start" ]
