import type { Metadata } from 'next'
import { Geist, Geist_Mono, JetBrains_Mono } from 'next/font/google'
import './globals.css'
import { ReactQueryProvider } from '../providers/ReactQueryProvider'
import { Toaster } from 'sonner'
import { ThemeProvider } from '../providers/theme-provider'

const jetbrainsMono = JetBrains_Mono({
	subsets: ['latin'],
	variable: '--font-sans',
})

const geistSans = Geist({
	variable: '--font-geist-sans',
	subsets: ['latin'],
})

const geistMono = Geist_Mono({
	variable: '--font-geist-mono',
	subsets: ['latin'],
})

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html
			lang='en'
			className={jetbrainsMono.variable}
			suppressHydrationWarning
		>
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased`}
			>
				<ThemeProvider
					attribute='class'
					defaultTheme='latte'
					value={{
						latte: 'latte',
						frappe: 'frappe',
						macchiato: 'macchiato',
						mocha: 'mocha',
					}}
				>
					<Toaster
						richColors
						toastOptions={{
							className: 'font-mono',
							style: {
								accentColor: 'var(--color-primary)',
								borderColor: 'var(--color-border)',
								borderRadius: 'var(--radius)',
								animation: 'both',
								fontFamily: 'var(--font-sans)',
							},
						}}
					/>
					<ReactQueryProvider>{children}</ReactQueryProvider>
				</ThemeProvider>
			</body>
		</html>
	)
}
